### ISSUE TITLE
When you upload an image and click on a file, the code sometimes doesn't display.

### ISSUE THREAD

**Issue by Bongs237** [CodePadSite/codepad-issues#2]

**Comment by stevenwhiz** [comment]
This issue still happens and need further investigation.  It doesn't appear to be that difficult for it to happen.

**Comment by Ethan-Vanderheijden** [comment]
After a file is uploaded, a new jstree node is created for it. This bug was likely due to some problem with creating that node.
I have rewritten the code that creates new jstree nodes for each uploaded file and have not noticed the issue.
