### ISSUE TITLE
Make all anonymous pads public and allow users to claim pads by logging in

### ISSUE THREAD

**Issue by Ethan-Vanderheijden** [CodePadSite/codepad-issues#36]
When a pad is made anonymously, the user seemingly has the option to select public or private on the sharing options page. However, an anonymous pad is always public, even when marked private, and therefore an anonymous pad should only have the public option available. One idea is to gray out the private option and put a link next to it asking the user to log in first.

If the user logs in or creates a new account while editing an anonymous pad, they should be able to "claim" the project for themselves. Of course, this should only happen if they are the same session that created the anonymous pad.

**Comment by Bongs237** [comment]
This can already be done by creating an account and duplicating or remixing the pad, since anyone has access to anonymous pads.
