### ISSUE TITLE
Anonymous pads on the featured page will show up with an author of "null".

### ISSUE THREAD

**Issue by Ethan-Vanderheijden** [CodePadSite/codepad-issues#50]
When a pad created by an anonymous user reaches the featured page, it will say the pad is by "null." If the user clicks on the link associated with "null," they will be taken to a 404 error page. This should be changed so that it says the pad is by "Anonymous" and there should be no profile page link attached.

**Comment by Bongs237** [comment]
Fixed in https://github.com/CodePadSite/codepad/pull/51, anonymous pads can no longer be featured
