### ISSUE TITLE
Give the user the ability to change profile pictures.

### ISSUE THREAD

**Issue by Ethan-Vanderheijden** [CodePadSite/codepad-issues#51]
On the user's profile page, the profile picture shows up but it is the default Codepad icon. Ideally, the user should be able to click on the profile picture and a file dialog should open up, through which the user can upload an image of their choice. An example of this profile picture UI is Discord's profile page.

**Comment by Bongs237** [comment]
Fixed in https://github.com/CodePadSite/codepad/pull/93
