### ISSUE TITLE
Unable to create a new file at the top level directory if only directories exist

### ISSUE THREAD

**Issue by stevenwhiz** [CodePadSite/codepad-issues#57]
My pad has the following:

example/
    Main.java

There is no way to create a new file at the top level directory.  Whether a click the new file icon or right click and select "Add file", it creates in the 'example' directory.

Workaround:
You can drag the new file to the top level directory.

**Comment by Ethan-Vanderheijden** [comment]
Closed with https://github.com/CodePadSite/codepad/pull/195
