### ISSUE TITLE
Extra character in input on Mac running Safari or on iPad

### ISSUE THREAD

**Issue by stevenwhiz** [CodePadSite/codepad-issues#60]
num = input('Enter number: ')
print(int(num))

This fails on iPad running Safari or Chrome, and fails on Mac running Safari but is okay on Chrome.  The error is:

Traceback (most recent call last):
  File "/home/bg62x3qw/main.py", line 2, in <module>
    print(int(num))
ValueError: invalid literal for int() with base 10: '\u200b5'

The problem stems from the extra character added in positioning the cursor on the screen.

**Comment by Ethan-Vanderheijden** [comment]
Closed with https://github.com/CodePadSite/codepad/pull/165
