### ISSUE TITLE
Be able to select which file to run

### ISSUE THREAD

**Issue by stlee987** [CodePadSite/codepad-issues#7]
Main.java is the default file for java projects and main.py is the default file for python projects. When the user runs their project, the main file is run by default and there is no way for them to specify which file they would like to run. For HTML projects, it will display the HTML file that is currently being edited unless the user is not editing an HTML file, at which point it will display index.html.

For java and python projects, the user should be able to create a custom run configuration that contains both the file they want to run and the arguments they want to supply. For HTML projects, the user should be able to set the extension that they want to view.

**Comment by Ethan-Vanderheijden** [comment]
Closed with pull request # 102 in main repository
